const content = [
  "A NÚCLEO CRM",
  "TERMOS DE USO EPOLÍTICA DE PRIVACIDADE",
  "Plataforma SaaS de CRM, automações e comunicações digitais",
  "Versão 1.0  •  Vigência: 23 de setembro de 2026",
  "Brasil",
  "LEITURA E ACEITE",
  "Ao criar conta, contratar um plano, acessar ou utilizar a Plataforma, o Cliente declara ter lido e aceito estes Termos de Uso e esta Política de Privacidade. Se o aceite for realizado em nome de uma empresa, a pessoa que o realiza declara possuir poderes para vinculá-la.",
  "SUMÁRIO EXECUTIVO",
  "Resumo das regras principais; a íntegra das cláusulas abaixo prevalece em caso de divergência.",
  "Tema",
  "Regra principal",
  "Natureza do serviço",
  "A Núcleo disponibiliza software de CRM e automação para organização de contatos, campanhas e comunicações digitais, inclusive por canais e integrações de terceiros.",
  "Responsabilidade pelas listas e campanhas",
  "O Cliente é responsável por origem da base, hipótese legal, transparência, conteúdo, segmentação, frequência, opt-out e demais requisitos aplicáveis às mensagens que envia.",
  "Papéis na LGPD",
  "Em regra, o Cliente é controlador dos dados dos contatos inseridos na Plataforma e a Núcleo atua como operadora; a Núcleo é controladora dos dados de conta, cobrança, suporte, segurança e relacionamento com seus próprios usuários.",
  "Integrações",
  "WhatsApp, SMS, e-mail, e-commerce, APIs, hospedagem e outros serviços podem depender de terceiros e de suas próprias regras, limites, preços e disponibilidade.",
  "Segurança",
  "A Núcleo adota medidas técnicas e administrativas compatíveis com o risco, mas nenhum ambiente digital é absolutamente imune a incidentes.",
  "Cancelamento",
  "Após o encerramento, o acesso poderá ser bloqueado e os dados serão exportados, retidos ou eliminados conforme estes Termos, a legislação e o prazo operacional definido.",
  "Uso proibido",
  "São vedados spam, listas obtidas ilicitamente, fraude, phishing, malware, conteúdo ilegal, violação de direitos e uso que prejudique a Plataforma, terceiros ou provedores integrados.",
  "PARTE I - TERMOS DE USO DA PLATAFORMA",
  "1. Objeto e escopo",
  "Estes Termos de Uso regulam o acesso, a contratação e a utilização da plataforma A Núcleo CRM, incluindo seus módulos de CRM, segmentação, criação e disparo de campanhas, automações, integrações, relatórios, APIs, recursos de suporte e funcionalidades que venham a ser adicionadas (“Plataforma”).",
  "A Plataforma é destinada primordialmente a uso profissional e empresarial. Funcionalidades específicas podem depender do plano contratado, disponibilidade técnica, integrações ativas e regras de terceiros.",
  "2. Definições",
  "“Cliente” ou “Contratante”: pessoa física empresária ou pessoa jurídica que contrata ou utiliza a Plataforma.",
  "“Usuário Autorizado”: pessoa indicada pelo Cliente para acessar a conta e utilizar funcionalidades em seu nome.",
  "“Contato” ou “Destinatário”: pessoa cujos dados são inseridos, sincronizados ou tratados pelo Cliente na Plataforma para fins de relacionamento, marketing, atendimento ou outras finalidades definidas pelo Cliente.",
  "“Dados do Cliente”: dados, arquivos, listas, conteúdos, configurações e informações enviados, coletados ou sincronizados pelo Cliente.",
  "“Campanha”: conjunto de mensagens, automações, segmentações ou comunicações configuradas pelo Cliente.",
  "“Integração”: conexão da Plataforma com serviços de terceiros, como provedores de mensageria, e-mail, SMS, WhatsApp, e-commerce, APIs, meios de pagamento, hospedagem ou analytics.",
  "“Conteúdo”: textos, imagens, links, ofertas, cupons, peças, arquivos, templates e demais materiais inseridos ou enviados pelo Cliente.",
  "3. Aceite, capacidade e representação",
  "O aceite destes Termos ocorre por meio eletrônico, inclusive mediante marcação de caixa de seleção, criação de conta, assinatura de proposta, contratação de plano, pagamento, acesso ou uso continuado da Plataforma.",
  "O Usuário que aceita estes Termos em nome de pessoa jurídica declara possuir poderes suficientes para representá-la. Se não possuir tais poderes, não deverá concluir a contratação ou utilizar a conta corporativa.",
  "A Núcleo poderá registrar evidências do aceite, incluindo data e hora, identificadores da conta, versão dos Termos, endereço IP, dispositivo ou outros registros tecnicamente disponíveis, observada a legislação aplicável.",
  "4. Cadastro, conta e credenciais",
  "O Cliente deverá fornecer informações verdadeiras, completas e atualizadas e manter seus dados cadastrais corretos.",
  "Credenciais são pessoais e não devem ser compartilhadas fora das permissões de acesso definidas pelo Cliente.",
  "O Cliente é responsável por definir perfis, permissões e desligar acessos de pessoas que deixem sua equipe.",
  "Suspeitas de uso não autorizado, comprometimento de senha ou acesso indevido devem ser comunicadas imediatamente à Núcleo.",
  "A Núcleo poderá exigir autenticação adicional, redefinição de senha ou validação de identidade quando necessário à segurança.",
  "5. Funcionalidades e evolução do serviço",
  "A Núcleo poderá aperfeiçoar, substituir, reorganizar, adicionar ou descontinuar funcionalidades, desde que preserve, quando razoavelmente possível, a essência do serviço contratado. Alterações relevantes que reduzam materialmente funcionalidades de planos pagos poderão ser comunicadas pelos canais cadastrados.",
  "Recursos identificados como beta, teste, experimental ou pré-lançamento podem apresentar instabilidade, limitações ou mudanças frequentes e poderão ser retirados a qualquer momento.",
  "6. Planos, preços, faturamento e pagamento",
  "Os preços, franquias, limites de uso, volumes, usuários, canais, créditos, mensagens, integrações e condições comerciais aplicáveis serão os informados na proposta, tela de contratação, pedido ou plano vigente. Valores de terceiros poderão ser cobrados separadamente ou repassados conforme a contratação.",
  "Salvo previsão comercial em sentido diverso, tributos incidentes sobre a prestação serão tratados conforme a legislação e os documentos fiscais aplicáveis. O Cliente é responsável por tributos e encargos relacionados ao seu próprio negócio e às campanhas que realizar.",
  "Em caso de inadimplemento, a Núcleo poderá, após comunicação razoável quando cabível, limitar funcionalidades, suspender disparos ou bloquear o acesso até a regularização, sem prejuízo da cobrança dos valores devidos.",
  "6.1 Renovação: quando o plano for recorrente, a renovação ocorrerá conforme a periodicidade contratada, até cancelamento nos termos aplicáveis.",
  "6.2 Reajustes: preços poderão ser reajustados mediante aviso prévio razoável e observância do instrumento comercial aplicável.",
  "6.3 Consumo por canal: créditos, custos ou tarifas de mensageria podem variar conforme operadora, país, tipo de mensagem, template, provedor ou mudanças impostas por terceiros.",
  "7. Responsabilidade do Cliente pelos Dados e pela base de contatos",
  "O Cliente determina quais dados serão inseridos na Plataforma, para que finalidades serão usados, quais pessoas serão contatadas e qual conteúdo será enviado. Por isso, o Cliente é responsável por assegurar que a coleta, importação, enriquecimento, segmentação, uso, compartilhamento e comunicação tenham fundamento jurídico e sejam compatíveis com a LGPD e demais normas aplicáveis.",
  "A utilização da Plataforma não torna uma base de dados lícita nem substitui avisos de privacidade, registros de consentimento, avaliações de legítimo interesse, contratos, políticas internas ou outros requisitos que sejam responsabilidade do Cliente.",
  "Não importar listas obtidas por vazamento, scraping ilícito, compra sem origem comprovável ou qualquer meio incompatível com a legislação ou com direitos de terceiros.",
  "Manter evidências da origem dos dados e da hipótese legal utilizada quando exigido ou recomendável.",
  "Respeitar pedidos de descadastro, oposição, bloqueio, correção e demais direitos aplicáveis.",
  "Evitar dados excessivos e restringir o tratamento ao necessário para a finalidade definida.",
  "Não inserir senhas, credenciais de terceiros, números completos de cartão, dados de autenticação financeira ou outras informações cuja inserção não seja necessária à finalidade do serviço.",
  "8. Comunicações por WhatsApp, SMS, e-mail e outros canais",
  "O Cliente é integralmente responsável por escolher destinatários, conteúdo, frequência e contexto das comunicações enviadas por meio da Plataforma. Deve cumprir a legislação, normas setoriais, direitos do consumidor e políticas dos canais e provedores utilizados.",
  "Sempre que aplicável, o Cliente deverá oferecer mecanismo claro de descadastro, oposição ou interrupção de mensagens e deverá honrar tais solicitações sem demora indevida.",
  "Obter consentimento ou outra hipótese legal adequada quando exigida para a comunicação pretendida.",
  "Usar apenas templates, remetentes, números, domínios e identidades autorizados.",
  "Não induzir o destinatário em erro sobre identidade, origem, finalidade, preço, oferta ou condição comercial.",
  "Não contornar limites, bloqueios, opt-outs, classificações de qualidade, políticas antispam ou medidas dos provedores.",
  "Não utilizar automações para assédio, perseguição, intimidação ou disparos desproporcionais.",
  "9. Uso aceitável e condutas proibidas",
  "Sem prejuízo do Anexo II, é proibido utilizar a Plataforma para atividades ilegais, abusivas, fraudulentas, invasivas ou que coloquem em risco a segurança, disponibilidade, reputação ou conformidade da Núcleo, de seus fornecedores ou de terceiros.",
  "spam, phishing, fraude, engenharia social, malware, ransomware, exploração de vulnerabilidades ou distribuição de código malicioso;",
  "violação de direitos autorais, marcas, segredos comerciais, privacidade, imagem, honra ou outros direitos;",
  "conteúdo discriminatório ilegal, ameaças, exploração sexual, incentivo a crimes ou qualquer conteúdo vedado por lei;",
  "tentativa de acessar contas, sistemas, dados ou funcionalidades sem autorização;",
  "engenharia reversa, cópia, extração massiva, scraping da Plataforma ou tentativa de burlar controles técnicos, salvo quando permitido por lei de forma irrenunciável;",
  "revenda não autorizada de acesso, compartilhamento de conta em desacordo com o plano ou uso que exceda limites técnicos deliberadamente;",
  "disparos que gerem índices anormais de reclamação, bloqueio, denúncia, rejeição ou reputação negativa em provedores.",
  "10. Integrações e serviços de terceiros",
  "A Plataforma pode integrar-se a serviços de terceiros. Esses serviços são regidos por seus próprios termos, políticas, limites, preços, procedimentos de autenticação e disponibilidade. O Cliente autoriza o intercâmbio dos dados necessários para executar a integração que voluntariamente ativar.",
  "A Núcleo não controla alterações, interrupções, bloqueios de conta, reprovações de template, limites de API, políticas ou decisões tomadas por terceiros. Sempre que possível, a Núcleo buscará oferecer alternativas ou orientações, sem assumir garantia sobre serviços externos.",
  "11. Disponibilidade, manutenção e suporte",
  "A Núcleo empregará esforços comercialmente razoáveis para manter a Plataforma disponível e segura. Poderão ocorrer indisponibilidades por manutenção, atualizações, incidentes, falhas de infraestrutura, provedores externos, telecomunicações, força maior ou eventos fora de controle razoável.",
  "Manutenções programadas relevantes poderão ser comunicadas antecipadamente quando viável. O suporte será prestado pelos canais e horários divulgados no plano ou na própria Plataforma.",
  "12. Propriedade intelectual",
  "A Núcleo e seus licenciantes detêm os direitos sobre a Plataforma, software, código, interface, marca, documentação, design, fluxos, modelos, métodos, componentes e materiais próprios, exceto conteúdos do Cliente e ativos de terceiros.",
  "Durante a vigência, é concedida ao Cliente licença limitada, revogável, não exclusiva, não sublicenciável e intransferível para utilizar a Plataforma conforme o plano contratado e estes Termos.",
  "O Cliente mantém a titularidade de seus dados, listas, marcas e conteúdos.",
  "O Cliente concede à Núcleo licença estritamente necessária para hospedar, processar, transmitir, reproduzir tecnicamente e executar o Conteúdo para prestar o serviço.",
  "Feedbacks e sugestões podem ser utilizados pela Núcleo para aprimorar o produto, sem obrigação de remuneração, desde que não revelem informação confidencial do Cliente.",
  "13. Confidencialidade",
  "Cada parte deverá proteger informações confidenciais da outra parte com grau de cuidado compatível com o utilizado para suas próprias informações de natureza semelhante e, no mínimo, com cuidado razoável. Informações confidenciais somente poderão ser usadas para executar a relação contratual ou cumprir obrigação legal.",
  "Não são consideradas confidenciais informações que sejam públicas sem violação deste documento, já fossem legitimamente conhecidas, sejam obtidas de terceiro legitimado ou tenham sido desenvolvidas de forma independente.",
  "14. Segurança da informação",
  "A Núcleo adotará medidas técnicas e administrativas razoáveis e compatíveis com a natureza dos dados e os riscos do tratamento, podendo incluir controles de acesso, gestão de credenciais, registros, segregação lógica, atualização de software, backups, monitoramento, criptografia quando apropriada e práticas de resposta a incidentes.",
  "O Cliente também é responsável pela segurança de suas credenciais, dispositivos, redes, usuários autorizados, integrações, chaves, tokens, domínios, números e configurações sob seu controle.",
  "15. Suspensão e medidas de proteção",
  "A Núcleo poderá suspender imediatamente, total ou parcialmente, a conta, campanhas, integrações ou funcionalidades quando houver indícios razoáveis de fraude, comprometimento de segurança, violação legal, risco relevante a titulares, abuso de canal, ameaça à infraestrutura, determinação de autoridade, inadimplemento grave ou violação material destes Termos.",
  "Quando a situação permitir, a Núcleo notificará o Cliente e dará oportunidade razoável de correção. Medidas urgentes podem ser tomadas antes da notificação para reduzir dano ou risco.",
  "16. Cancelamento, encerramento, exportação e eliminação de dados",
  "O Cliente poderá solicitar cancelamento pelos meios disponibilizados. O efeito financeiro seguirá a proposta, ciclo contratado e regras aplicáveis ao plano. Após o encerramento, o acesso poderá ser bloqueado e automações ativas poderão ser interrompidas.",
  "Salvo exigência legal, disputa, investigação, prevenção a fraude, obrigação de guarda ou instrução válida em sentido diverso, os Dados do Cliente serão eliminados ou anonimizados após o período operacional de retenção. Antes disso, a Núcleo poderá permitir exportação por prazo de 30 dias, desde que tecnicamente disponível e observados limites do plano.",
  "17. Declarações e limitações do serviço",
  "A Plataforma é uma ferramenta tecnológica e não presta assessoria jurídica, tributária, regulatória, de marketing, de telecomunicações ou de proteção de dados. Relatórios, métricas, automações e sugestões não substituem análise profissional do Cliente.",
  "A Núcleo não garante resultado comercial, aumento de vendas, entrega de todas as mensagens, abertura, clique, conversão, ausência de bloqueios de canal ou disponibilidade ininterrupta de integrações de terceiros.",
  "18. Responsabilidade e limitação de danos",
  "Cada parte responde pelos danos diretos que causar à outra por descumprimento de suas obrigações, na forma da legislação aplicável. A Núcleo não responde por decisões comerciais do Cliente, conteúdo de campanhas, origem ilícita de listas, instruções do Cliente, atos de Usuários Autorizados, falhas de terceiros fora de seu controle ou uso contrário a estes Termos.",
  "Na máxima extensão permitida pela lei, ficam excluídos danos indiretos, lucros cessantes, perda de oportunidade, perda de receita esperada ou danos consequenciais que não decorram diretamente de conduta imputável à parte responsável.",
  "18.1 Limite contratual: ressalvadas hipóteses em que a limitação seja vedada por lei, fraude, dolo, violação intencional de confidencialidade ou obrigações de proteção de dados imputáveis à Núcleo, a responsabilidade contratual agregada da Núcleo será limitada ao total efetivamente pago pelo Cliente à Núcleo nos 12 meses anteriores ao evento que deu origem à reclamação.",
  "19. Indenização por condutas do Cliente",
  "Na medida permitida pela lei, o Cliente deverá ressarcir a Núcleo por prejuízos, custos e despesas razoavelmente comprovados decorrentes de reclamações de terceiros, sanções, bloqueios de canal ou demandas causadas diretamente por conteúdo, bases, campanhas, instruções, produtos ou práticas do Cliente que violem a lei, direitos de terceiros ou estes Termos, assegurado o direito de defesa e participação do Cliente no tratamento da reclamação.",
  "20. Alterações destes Termos",
  "A Núcleo poderá atualizar estes Termos para refletir mudanças legais, regulatórias, operacionais, comerciais, de segurança ou de funcionalidades. A versão vigente indicará a data de atualização. Alterações materiais serão comunicadas por meio razoável, como e-mail, aviso na Plataforma ou área de conta.",
  "O uso continuado após a entrada em vigor das alterações representará aceite da nova versão, ressalvados direitos inderrogáveis e hipóteses em que seja exigido novo consentimento ou aceite destacado.",
  "21. Comunicações entre as partes",
  "Avisos operacionais, de segurança, cobrança, suporte e alterações contratuais poderão ser enviados aos contatos cadastrados na conta. O Cliente deve manter seus dados atualizados. Notificações legais poderão seguir os meios previstos no contrato, na Plataforma ou na legislação.",
  "22. Legislação aplicável e foro",
  "Estes Termos são regidos pelas leis da República Federativa do Brasil. As partes buscarão resolver controvérsias de boa-fé por canais de suporte e negociação.",
  "22.1 Foro: quando válida a eleição de foro, fica eleito o foro da Comarca de São Paulo/SP, com renúncia a qualquer outro, sem prejuízo de foro obrigatório previsto em lei.",
  "23. Disposições gerais",
  "A tolerância a um descumprimento não implica renúncia de direito.",
  "A invalidade de uma cláusula não invalida as demais; a disposição afetada deverá ser interpretada na máxima extensão legal possível.",
  "O Cliente não poderá ceder sua conta ou posição contratual sem autorização da Núcleo, salvo reorganização societária que não prejudique a execução e mediante comunicação quando aplicável.",
  "A Núcleo poderá ceder o contrato em reorganização, investimento, fusão, aquisição ou transferência do negócio, preservadas as obrigações essenciais e a legislação de dados.",
  "Em caso de conflito entre estes Termos e proposta comercial específica assinada, prevalece a proposta quanto às condições comerciais específicas e estes Termos quanto às regras gerais, salvo previsão expressa em contrário.",
  "ANEXO I - ACORDO DE TRATAMENTO DE DADOS (DPA)",
  "Integra estes Termos e aplica-se quando a Núcleo tratar dados pessoais em nome do Cliente.",
  "A1. Objeto e instruções",
  "O Cliente, na qualidade de controlador, instrui a Núcleo a tratar os dados pessoais necessários para disponibilizar CRM, segmentação, campanhas, automações, integrações, suporte técnico e demais funcionalidades contratadas. A Núcleo tratará os dados de acordo com instruções documentadas do Cliente, estes Termos e a legislação aplicável, salvo obrigação legal em sentido diverso.",
  "A2. Detalhes do tratamento",
  "Natureza e finalidade: armazenamento, organização, consulta, segmentação, transmissão, integração, registro de eventos, automação e outras operações necessárias à prestação do serviço.",
  "Duração: vigência da relação contratual e períodos posteriores estritamente necessários para exportação, eliminação, segurança, exercício de direitos e obrigações legais.",
  "Categorias de titulares: leads, consumidores, clientes, representantes, empregados, prestadores, parceiros e demais pessoas cujos dados o Cliente decida inserir.",
  "Categorias de dados: dados de identificação e contato, histórico de relacionamento, preferências, tags, campos personalizados, eventos de compra, dados transacionais limitados, interações e outros dados configurados pelo Cliente.",
  "Dados sensíveis: não constituem requisito padrão da Plataforma. O Cliente deve evitar inserir dados pessoais sensíveis salvo quando estritamente necessário, permitido pelo plano e amparado em hipótese legal adequada.",
  "A3. Obrigações da Núcleo como operadora",
  "tratar dados somente para prestar o serviço e conforme instruções lícitas do Cliente;",
  "assegurar deveres de confidencialidade a pessoas autorizadas a tratar os dados;",
  "adotar medidas técnicas e administrativas de segurança compatíveis com o risco;",
  "apoiar razoavelmente o Cliente no atendimento a direitos dos titulares, incidentes e obrigações regulatórias, considerando a natureza do tratamento e as informações disponíveis;",
  "informar o Cliente se considerar que uma instrução viola a legislação aplicável, sem obrigação de prestar parecer jurídico;",
  "manter registros e evidências necessárias ao cumprimento de suas obrigações legais e contratuais;",
  "eliminar ou devolver dados ao final, ressalvadas obrigações legais, backups seguros e retenções permitidas.",
  "A4. Obrigações do Cliente como controlador",
  "definir finalidades e bases legais e fornecer avisos de privacidade adequados;",
  "assegurar que instruções dadas à Núcleo sejam lícitas e documentadas;",
  "responder diretamente aos titulares e à ANPD quando a lei lhe atribuir essa obrigação;",
  "não solicitar tratamento incompatível com estes Termos, com a finalidade contratada ou com a lei;",
  "manter canais e procedimentos para opt-out, oposição, correção, exclusão e demais direitos;",
  "avaliar riscos específicos de campanhas, perfis, dados sensíveis, menores ou setores regulados.",
  "A5. Suboperadores",
  "O Cliente autoriza de forma geral a utilização de suboperadores necessários à prestação do serviço. A Núcleo celebrará instrumentos que imponham obrigações de proteção de dados compatíveis com o papel desempenhado por cada fornecedor. Quando tecnicamente e comercialmente viável, mudanças relevantes poderão ser divulgadas por lista de suboperadores ou comunicação ao Cliente.",
  "A6. Transferência internacional",
  "Se um suboperador ou infraestrutura estiver fora do Brasil e houver transferência internacional sujeita à LGPD, a Núcleo adotará mecanismo legal válido e as medidas de transparência aplicáveis. Se necessário, as partes cooperarão para incorporar cláusulas-padrão aprovadas pela ANPD ou outro instrumento exigido.",
  "A7. Incidentes de segurança",
  "Ao tomar conhecimento de incidente confirmado envolvendo dados pessoais do Cliente e relevante à atuação da Núcleo como operadora, a Núcleo notificará o Cliente sem demora indevida, pelos contatos cadastrados ou canal de segurança, contendo, na medida em que estiverem disponíveis, natureza do incidente, categorias de dados, possíveis impactos, medidas adotadas e ponto de contato.",
  "O Cliente permanece responsável pelas decisões e comunicações exigidas de controlador, salvo quando a lei atribuir obrigação diretamente à Núcleo em determinado contexto. A cooperação não implica admissão de culpa ou responsabilidade.",
  "A8. Solicitações de titulares e autoridades",
  "Se a Núcleo receber solicitação de titular relacionada a dados controlados pelo Cliente, poderá redirecioná-la ao Cliente ou fornecer canal de contato do controlador, salvo obrigação legal em contrário. A Núcleo prestará assistência técnica razoável para localização, exportação, correção, bloqueio ou exclusão quando a funcionalidade e a relação contratual permitirem.",
  "Ordens de autoridades serão tratadas conforme a legislação. Quando legalmente permitido, a Núcleo poderá comunicar o Cliente antes de fornecer dados controlados por ele.",
  "A9. Auditoria e evidências",
  "Mediante solicitação razoável, proporcional e relacionada ao tratamento, a Núcleo poderá fornecer informações disponíveis sobre suas medidas de segurança e conformidade. Auditorias presenciais ou testes intrusivos dependerão de acordo específico quanto a escopo, confidencialidade, segurança, custos e impacto operacional.",
  "O Cliente não poderá realizar testes de invasão, varreduras ou avaliações técnicas que afetem a Plataforma sem autorização prévia e escrita.",
  "A10. Devolução e eliminação",
  "Encerrada a prestação, a Núcleo eliminará ou anonimizará os dados pessoais tratados como operadora após o prazo operacional definido, salvo se a retenção for exigida por lei, ordem válida, segurança, exercício de direitos ou houver instrução legítima do Cliente para exportação dentro do prazo disponível. Backups poderão ser eliminados de acordo com ciclos técnicos de retenção e permanecerão protegidos até sua sobrescrita.",
  "ANEXO II - POLÍTICA DE USO ACEITÁVEL E COMUNICAÇÕES",
  "B1. Princípios de campanha",
  "identificação clara do remetente e da finalidade da mensagem;",
  "frequência razoável e compatível com a expectativa do destinatário;",
  "segmentação coerente com a origem dos dados e o relacionamento existente;",
  "mecanismo de opt-out quando aplicável e lista de supressão atualizada;",
  "links e domínios confiáveis, sem técnicas enganosas;",
  "respeito a horários, restrições setoriais e preferências do destinatário quando aplicáveis;",
  "proibição de reutilizar contatos que já tenham se oposto, salvo nova base jurídica válida e contexto compatível.",
  "B2. Conteúdos e setores de maior risco",
  "O Cliente deve realizar análise jurídica específica antes de utilizar a Plataforma em campanhas envolvendo dados sensíveis, saúde, crédito, serviços financeiros, apostas, produtos regulados, crianças e adolescentes, telecomunicações, política eleitoral, ou outros setores sujeitos a regras especiais. A Núcleo poderá exigir comprovações, limitar funcionalidades ou recusar campanhas quando houver risco regulatório, de segurança ou reputacional.",
  "B3. Reputação e qualidade dos canais",
  "A Núcleo poderá aplicar limites, rate limits, bloqueios temporários, revisão de templates, verificação adicional ou outras medidas quando indicadores apontarem reclamações, denúncias, bounces, bloqueios ou risco de suspensão por provedor. Essas medidas visam proteger a entregabilidade e a continuidade do serviço para todos os clientes.",
  "B4. Lista de verificação mínima antes do disparo",
  "Tenho origem comprovável da lista?",
  "Tenho hipótese legal adequada para esta finalidade e canal?",
  "O destinatário foi informado de forma adequada sobre o tratamento?",
  "Existe opt-out ou oposição quando aplicável?",
  "A mensagem identifica minha empresa e não induz a erro?",
  "A segmentação não utiliza dados excessivos ou sensíveis sem necessidade?",
  "O conteúdo e o produto ofertado são legais e compatíveis com as políticas do canal?",
  "Minha equipe sabe como tratar pedidos de exclusão, oposição e privacidade?",
];

const isMajorHeading = (line: string) =>
  line === line.toUpperCase() && /[A-ZÁÀÂÃÉÊÍÓÔÕÚÇ]/.test(line) && line.length > 8;

const isSectionHeading = (line: string) =>
  /^\d+(\.\d+)?\.\s/.test(line) || /^Anexo\s/i.test(line) || /^A\d+\.|^B\d+\./.test(line);

const Terms = () => {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-900">
      <section className="border-b bg-white">
        <div className="mx-auto max-w-4xl px-6 py-10">
          <a href="/" className="text-sm font-medium text-primary hover:underline">Voltar para a Núcleo CRM</a>
          <h1 className="mt-6 text-3xl font-bold tracking-tight sm:text-4xl">Termos de Uso</h1>
          <p className="mt-3 text-sm text-slate-600">Versão 1.0 · Vigência: 23 de setembro de 2026</p>
        </div>
      </section>
      <article className="mx-auto max-w-4xl px-6 py-10">
        <div className="rounded-lg border bg-white p-6 shadow-sm sm:p-8">
          {content.map((line, index) => {
            if (index === 0) {
              return <h2 key={index} className="mb-5 text-2xl font-semibold text-slate-950">{line}</h2>;
            }
            if (isMajorHeading(line)) {
              return <h2 key={index} className="mb-4 mt-9 text-xl font-semibold text-slate-950">{line}</h2>;
            }
            if (isSectionHeading(line)) {
              return <h3 key={index} className="mb-2 mt-6 text-lg font-semibold text-slate-900">{line}</h3>;
            }
            return <p key={index} className="mb-3 text-sm leading-7 text-slate-700">{line}</p>;
          })}
        </div>
      </article>
    </main>
  );
};

export default Terms;
